### ISSUE TITLE
Add support for WHO=7 messages

### ISSUE THREAD

**Issue by ste94pz** [anotherjulien/OWNd#1]
[WHO_7.pdf](https://github.com/anotherjulien/OWNd/files/5978475/WHO_7.pdf)

Hi, could you add the support for sending messages to the multimedia system (WHO=7)? I need to send the message to enable the camera of the entryphone (\*7\*0*WHERE##). Thank you! :)

**Comment by anotherjulien** [comment]
Do you need to use this with the Home Assistant integration?
If so, your best bet short term will be to use the 'send_message' service to send any arbitrary message.

**Comment by ste94pz** [comment]
> Do you need to use this with the Home Assistant integration?
> 
> If so, your best bet short term will be to use the 'send_message' service to send any arbitrary message.

Yes, I tried but it doesn't send it. It gives me this error if I try to send \*7\*0*4000##

![image](https://user-images.githubusercontent.com/49609029/108160168-de588980-70e8-11eb-9b8f-42c732a9a171.png)
![image](https://user-images.githubusercontent.com/49609029/108160179-e3b5d400-70e8-11eb-809a-50e38a21ee6f.png)

**Comment by anotherjulien** [comment]
Ah yes, I see.
Let me work on that, I'll let you know when I've made progress!

**Comment by anotherjulien** [comment]
Provisions have been added for most if not all command messages, even those not yet with built-in helpers.
This is available in OWNd 0.7.22, the requirement is present in the latest MyHome integration master but can also be added manually in `manifest.json`.

**Comment by ste94pz** [comment]
Hi, sorry to bother you, but it still doesn't work, I get the same error. I think that the problem is the message beeing marked as an OWNEvent, instead you added the who=7 definitions in the OWNCommand class.

**Comment by anotherjulien** [comment]
The problem is that for status, command and event are exactly the same, so I cannot differentiate between them.
However, it makes no sense (I think...) to send event from Home Assistant, so I fixed this problem in the integration's newly published master, by parsing the input as a command directly, rather than a generic message.
