### ISSUE TITLE
Error on installing in HACS

### ISSUE THREAD

**Issue by Fedo-be** [anotherjulien/OWNd#3]
![image](https://user-images.githubusercontent.com/35451617/147615663-a9c7c33a-9761-42e1-929d-84ad5635debf.png)
When adding the link to the "Custom respositories", I get an error that the structure is not compliant.
The other project MyHome didn't give this error and got well installed.

Did I do something wrong?

**Comment by caiosweet** [comment]
This is the python repository library.
The correct link to use in hacs is
 https://github.com/anotherjulien/MyHOME

**Comment by Fedo-be** [comment]
I thought I had to install both of them, to make it work.
Thank you for your contribution
